services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    depends_on:
      supertokens:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env

  nest-postgres:
    image: 'postgres:latest'
    container_name: nest-postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - app_network
    volumes:
      - nest-postgres:/var/lib/postgresql/data
      - .docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  nest-postgres:
    name: nest-postgres-db
