services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    depends_on:
      supertokens:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    container_name: supertokens
    depends_on:
      nest-postgres:
        condition: service_healthy
    ports:
      - 3567:3567
    env_file:
      - .env
    restart: always
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nHost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  nest-postgres:
    image: 'postgres:latest'
    container_name: nest-postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - nest-postgres:/var/lib/postgresql/data
      - .docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nest-postgres:
    name: nest-postgres-db
