#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${APP_DB};

  CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
  ALTER USER ${APP_USER} CREATEDB;

  GRANT ALL PRIVILEGES ON DATABASE ${APP_DB} TO ${APP_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${APP_DB}" <<-EOSQL
  GRANT USAGE ON SCHEMA public TO ${APP_USER};
  GRANT CREATE ON SCHEMA public TO ${APP_USER};
EOSQL
