#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${APP_DB};
  CREATE DATABASE ${SUPERTOKENS_DB};

  CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
  ALTER USER ${APP_USER} CREATEDB;
  CREATE USER ${SUPERTOKENS_USER} WITH PASSWORD '${SUPERTOKENS_PASSWORD}';

  GRANT ALL PRIVILEGES ON DATABASE ${APP_DB} TO ${APP_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${SUPERTOKENS_DB} TO ${SUPERTOKENS_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${APP_DB}" <<-EOSQL
  GRANT USAGE ON SCHEMA public TO ${APP_USER};
  GRANT CREATE ON SCHEMA public TO ${APP_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="${SUPERTOKENS_DB}" <<-EOSQL
  GRANT USAGE ON SCHEMA public TO ${SUPERTOKENS_USER};
  GRANT CREATE ON SCHEMA public TO ${SUPERTOKENS_USER};
EOSQL
